export const ageRanges = [
  '18-20',
  '20-25',
  '25-30',
  '30-35',
  '35-40',
  '40-45',
  '45-50',
  '50+'
]

// https://www.reddit.com/r/MyHeritage/comments/1e41mrz/ethnicity_wishlist_this_is_the_list_of/



export const ethnicities = [
  'White / European Ancestry',
  'Black / African Ancestry',
  'East Asian',
  'South Asian',
  'Southeast Asian',
  'Middle Eastern / North African (MENA)',
  'Latinx / Hispanic',
  'Indigenous / First Nations',
  'Australian, Māori, Pacific Islander',
  'Mixed / Multiethnic',
  'Jewish Ancestry',
  'Other',
  'Prefer not to say / Unknown'
]

export const diagnosisMethods = [
  'Doctor',
  'Research',
  'Other'
]

export const conditionsList = [
  'Abdominal aortic aneurysm',
  'Achilles tendinopathy',
  'Acne',
  'Acute cholecystitis',
  'Acute lymphoblastic leukaemia',
  'Acute lymphoblastic leukaemia: Children',
  'Acute lymphoblastic leukaemia: Teenagers and young adults',
  'Acute myeloid leukaemia',
  'Acute myeloid leukaemia: Children',
  'Acute myeloid leukaemia: Teenagers and young adults',
  'Acute pancreatitis',
  'Addison\'s disease',
  'Adenomyosis',
  'Alcohol-related liver disease',
  'Allergic rhinitis',
  'Allergies',
  'Alzheimer\'s disease',
  'Anal cancer',
  'Anaphylaxis',
  'Angina',
  'Angioedema',
  'Ankle avulsion fracture',
  'Ankle sprain',
  'Ankylosing spondylitis',
  'Anorexia nervosa',
  'Anxiety',
  'Anxiety disorders in children',
  'Aplastic anaemia',
  'Appendicitis',
  'Arterial thrombosis',
  'Arthritis',
  'Asbestosis',
  'Asthma',
  'Ataxia',
  'Atopic eczema',
  'Atrial fibrillation',
  'Attention deficit hyperactivity disorder (ADHD)',
  'Autism',
  'Back problems',
  'Bacterial vaginosis',
  'Benign prostate enlargement',
  'Bile duct cancer (cholangiocarcinoma)',
  'Binge eating',
  'Bipolar disorder',
  'Bladder cancer',
  'Blood poisoning (sepsis)',
  'Bone cancer',
  'Bone cancer: Teenagers and young adults',
  'Bowel cancer',
  'Bowel incontinence',
  'Bowel polyps',
  'Brain stem death',
  'Brain tumours',
  'Brain tumours: Children',
  'Brain tumours: Teenagers and young adults',
  'Breast cancer (female)',
  'Breast cancer (male)',
  'Bronchiectasis',
  'Bronchitis',
  'Bulimia nervosa',
  'Bunion',
  'Carcinoid syndrome and carcinoid tumours',
  'Cardiovascular disease',
  'Carpal tunnel syndrome',
  'Catarrh',
  'Cellulitis',
  'Cerebral palsy',
  'Cervical cancer',
  'Cervical spondylosis',
  'Chest and rib injury',
  'Chest infection',
  'Chickenpox',
  'Chilblains',
  'Chlamydia',
  'Chronic fatigue syndrome',
  'Chronic kidney disease',
  'Chronic lymphocytic leukaemia',
  'Chronic myeloid leukaemia',
  'Chronic obstructive pulmonary disease (COPD)',
  'Chronic pain',
  'Chronic pancreatitis',
  'Cirrhosis',
  'Clavicle (collar bone) fracture',
  'Clostridium difficile',
  'Coeliac disease',
  'Cold sore',
  'Coma',
  'Common cold',
  'Concussion',
  'Congenital heart disease',
  'Conjunctivitis',
  'Constipation',
  'Coronary heart disease',
  'Coronavirus (COVID-19)',
  'Coronavirus (COVID-19): Longer-term effects (long COVID)',
  'Costochondritis',
  'Cough',
  'Crohn\'s disease',
  'Croup',
  'Cystic fibrosis',
  'Cystitis',
  'Yellow fever',
  'Zika virus',
  'Other',
  'Deafblindness',
  'Deep vein thrombosis',
  'Degenerative cervical myelopathy',
  'Dehydration',
  'Delirium',
  'Dementia',
  'Dental abscess',
  'Depression',
  'Dermatitis herpetiformis',
  'Diabetic retinopathy',
  'Diarrhoea',
  'Discoid eczema',
  'Diverticular disease and diverticulitis',
  'Dizziness (Lightheadedness)',
  'Down\'s syndrome',
  'Dry mouth',
  'Dysphagia (swallowing problems)',
  'Dystonia',
  'Earache',
  'Early miscarriage',
  'Earwax build-up',
  'Ebola virus disease',
  'Ectopic pregnancy',
  'Edwards\' syndrome',
  'Elbow (radial head or neck) fracture',
  'Endometriosis',
  'Epilepsy',
  'Erectile dysfunction (impotence)',
  'Escherichia coli (E. coli) O157',
  'Ewing sarcoma',
  'Ewing sarcoma: Children',
  'Eye cancer',
  'Eating disorders',
  'Farting',
  'Febrile seizures',
  'Feeling of something in your throat (Globus)',
  'Fever in adults',
  'Fever in children',
  'Fibroids',
  'Fibromyalgia',
  'Flu',
  'Foetal alcohol syndrome',
  'Food allergy',
  'Food poisoning',
  'Fragility fracture of the hip',
  'Frozen shoulder',
  'Functional neurological disorder (FND)',
  'Fungal nail infection',
  'Gallbladder cancer',
  'Gallstones',
  'Ganglion cyst',
  'Gastroenteritis',
  'Gastro-oesophageal reflux disease (GORD)',
  'Genital herpes',
  'Genital symptoms',
  'Genital warts',
  'Germ cell tumours',
  'Glandular fever',
  'Golfers elbow',
  'Gonorrhoea',
  'Gout',
  'Greater trochanteric pain syndrome',
  'Gum disease',
  'Haemorrhoids (piles)',
  'Hand, foot and mouth disease',
  'Hay fever',
  'Head and neck cancer',
  'Head lice and nits',
  'Headaches',
  'Hearing loss',
  'Heart attack',
  'Heart block',
  'Heart failure',
  'Heart palpitations',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis C',
  'Hiatus hernia',
  'High blood pressure (hypertension)',
  'High cholesterol',
  'HIV',
  'Hives',
  'Hodgkin lymphoma',
  'Hodgkin lymphoma: Children',
  'Hodgkin lymphoma: Teenagers and young adults',
  'Huntington\'s disease',
  'Hydrocephalus',
  'Hyperglycaemia (high blood sugar)',
  'Hyperhidrosis',
  'Hypoglycaemia (low blood sugar)',
  'Idiopathic pulmonary fibrosis',
  'Impetigo',
  'Indigestion',
  'Infertility',
  'Inflammatory bowel disease (IBD)',
  'Inherited heart conditions',
  'Insomnia',
  'Iron deficiency anaemia',
  'Irritable bowel syndrome (IBS)',
  'Itching',
  'Itchy bottom',
  'Itchy skin',
  'Joint hypermobility',
  'Kaposi\'s sarcoma',
  'Kidney cancer',
  'Kidney infection',
  'Kidney stones',
  'Labyrinthitis',
  'Lactose intolerance',
  'Laryngeal (larynx) cancer',
  'Laryngitis',
  'Late miscarriage',
  'Leg cramps',
  'Lichen planus',
  'Lipoedema',
  'Liver cancer',
  'Liver disease',
  'Liver tumours',
  'Long-term effects of COVID-19',
  'Loss of libido',
  'Low blood pressure',
  'Lung cancer',
  'Lupus',
  'Lyme disease',
  'Lymphoedema',
  'Lymphogranuloma venereum (LGV)',
  'Malaria',
  'Malignant brain tumour (cancerous)',
  'Malnutrition',
  'Measles',
  'Meningitis',
  'Meniere\'s disease',
  'Menopause',
  'Mesothelioma',
  'Metacarpal fracture of the hand',
  'Middle ear infection (otitis media)',
  'Migraine',
  'Minor head injury',
  'Miscarriage',
  'Molar pregnancy',
  'Motor neurone disease (MND)',
  'Mouth cancer',
  'Mouth ulcer',
  'Multiple myeloma',
  'Multiple sclerosis (MS)',
  'Multiple system atrophy (MSA)',
  'Mumps',
  'Munchausen\'s syndrome',
  'Muscular dystrophy',
  'Myalgic encephalomyelitis (ME)',
  'Myasthenia gravis',
  'Nasal and sinus cancer',
  'Nasopharyngeal cancer',
  'Neck injury',
  'Neck problems',
  'Neuroblastoma: Children',
  'Neuroendocrine tumours',
  'Non-alcoholic fatty liver disease (NAFLD)',
  'Non-Hodgkin lymphoma',
  'Non-Hodgkin lymphoma: Children',
  'Norovirus',
  'Nosebleed',
  'Obesity',
  'Obsessive compulsive disorder (OCD)',
  'Obstructive sleep apnoea',
  'Oesophageal cancer',
  'Oral thrush in adults',
  'Osteoarthritis',
  'Osteoarthritis of the hip',
  'Osteoarthritis of the knee',
  'Osteoarthritis of the thumb',
  'Osteoporosis',
  'Osteosarcoma',
  'Outer ear infection (otitis externa)',
  'Ovarian cancer',
  'Ovarian cancer: Teenagers and young adults',
  'Ovarian cyst',
  'Overactive thyroid',
  'Pain in the ball of the foot',
  'Paget\'s disease of the nipple',
  'Pancreatic cancer',
  'Panic disorder',
  'Parkinson\'s disease',
  'Patau\'s syndrome',
  'Patellofemoral pain syndrome',
  'Pelvic inflammatory disease',
  'Pelvic organ prolapse',
  'Penile cancer',
  'Peripheral neuropathy',
  'Personality disorder',
  'PIMS',
  'Plantar heel pain',
  'Pleurisy',
  'Pneumonia',
  'Polio',
  'Polycystic ovary syndrome (PCOS)',
  'Polymyalgia rheumatica',
  'Post-concussion syndrome',
  'Post-polio syndrome',
  'Post-traumatic stress disorder (PTSD)',
  'Postural orthostatic tachycardia syndrome (PoTS)',
  'Postnatal depression',
  'Premenstrual Dysphoric Disorder (PMDD)',
  'Pressure ulcers',
  'Progressive supranuclear palsy (PSP)',
  'Prostate cancer',
  'Psoriasis',
  'Psoriatic arthritis',
  'Psychosis',
  'Pubic lice',
  'Pulmonary hypertension',
  'Phobias',
  'Raynaud\'s phenomenon',
  'Reactive arthritis',
  'Recurrent miscarriage',
  'Restless legs syndrome',
  'Respiratory syncytial virus (RSV)',
  'Retinoblastoma: Children',
  'Rhabdomyosarcoma',
  'Rheumatoid arthritis',
  'Ringworm and other fungal infections',
  'Rosacea',
  'Scabies',
  'Scarlet fever',
  'Schizophrenia',
  'Sciatica',
  'Scoliosis',
  'Seasonal affective disorder (SAD)',
  'Sepsis',
  'Septic shock',
  'Severe head injury',
  'Shingles',
  'Shortness of breath',
  'Sickle cell disease',
  'Sinusitis',
  'Sjogren\'s syndrome',
  'Skin cancer (melanoma)',
  'Skin cancer (non-melanoma)',
  'Skin light sensitivity (photosensitivity)',
  'Slapped cheek syndrome',
  'Soft tissue sarcomas',
  'Soft tissue sarcomas: Teenagers and young adults',
  'Sore throat',
  'Spina bifida',
  'Spinal stenosis',
  'Spleen problems and spleen removal',
  'Stillbirth',
  'Stomach ache and abdominal pain',
  'Stomach cancer',
  'Stomach ulcer',
  'Streptococcus A (strep A)',
  'Stress, anxiety and low mood',
  'Stroke',
  'Subacromial pain syndrome',
  'Sudden infant death syndrome (SIDS)',
  'Suicide',
  'Sunburn',
  'Supraventricular tachycardia',
  'Swollen glands',
  'Syphilis',
  'Self-harm',
  'Tennis elbow',
  'Testicular cancer',
  'Testicular cancer: Teenagers and young adults',
  'Testicular lumps and swellings',
  'Thirst',
  'Threadworms',
  'Thrush',
  'Thumb fracture',
  'Thyroid cancer',
  'Thyroid cancer: Teenagers and young adults',
  'Tick bites',
  'Tinnitus',
  'Tonsillitis',
  'Tooth decay',
  'Toothache',
  'Tourette\'s syndrome',
  'Transient ischaemic attack (TIA)',
  'Transverse myelitis',
  'Trichomonas infection',
  'Trigeminal neuralgia',
  'Tuberculosis (TB)',
  'Type 1 diabetes',
  'Type 2 diabetes',
  'Ulcerative colitis',
  'Underactive thyroid',
  'Urinary incontinence',
  'Urinary incontinence in women',
  'Urinary tract infection (UTI)',
  'Urinary tract infection (UTI) in children',
  'Urticaria (hives)',
  'Vaginal cancer',
  'Vaginal discharge',
  'Varicose eczema',
  'Varicose veins',
  'Venous leg ulcer',
  'Vertigo',
  'Vitamin B12 or folate deficiency anaemia',
  'Vomiting in adults',
  'Vomiting in children and babies',
  'Vulval cancer',
  'Vulvodynia',
  'Warts and verrucas',
  'Whiplash',
  'Whooping cough',
  'Wilms\' tumour',
  'Wolff-Parkinson-White syndrome',
  'Womb (uterus) cancer',
  'Wrist fracture',
  'Yellow fever',
  'Zika virus',
  'Other'
]

export const medicationOptions = [
  'None',
  'Analgesics',
  'Antacids',
  'Antianxiety Drugs',
  'Antiarrhythmics',
  'Antibacterials',
  'Antibiotics',
  'Anticoagulants',
  'Anticonvulsants',
  'Antidepressants',
  'Antidiarrheals',
  'Antiemetics',
  'Antifungals',
  'Antihistamines',
  'Antihypertensives',
  'Anti-Inflammatories',
  'Antineoplastics',
  'Antipsychotics',
  'Antipyretics',
  'Antivirals',
  'Beta-Blockers',
  'Bronchodilators',
  'Cold Medicines',
  'Corticosteroids',
  'Cough Suppressants',
  'Decongestants',
  'Diuretics',
  'Expectorants',
  'Hormones',
  'Hypoglycemics',
  'Immunosuppressives',
  'Laxatives',
  'Muscle Relaxants',
  'Sedatives',
  'Sex Hormones',
  'Sleeping Medications',
  'Vitamins',
  'Other'
]

export const treatmentOptions = [
  'CBT',
  'Medication',
  'Lifestyle Changes',
  'Other'
]

export const symptomDateRanges = [
  '0-5 years old',
  '6-10 years old',
  '11-15 years old',
  '16-20 years old',
  '21-25 years old',
  '26+ years old'
]

export const moodOptions = [
  'Great',
  'Good',
  'Okay',
  'Not Great',
  'Bad'
] 